### ISSUE TITLE
Cannot find module '../plugin/wodi'

### ISSUE THREAD

**Issue by jshensh** [gismanli/NodeQQ#1]
第一次报错：

```
/root/NodeQQ/src/group.js:107
         else {
         ^^^^

SyntaxError: Unexpected token else
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/NodeQQ/src/poll.js:9:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

注释掉

```
     else {
        var tuling = 'http://www.tuling123.com/openapi/api?key=873ba8257f7835dfc537090fa4120d14&info=' + encodeURI(val.trim());
        client.url_get(tuling, function(err, res, info) {
            self.sendGroupMsg(msg.group_code, JSON.parse(info).text);
        });
     }
```

以后，又爆了个

```
module.js:327
    throw err;
    ^

Error: Cannot find module '../plugin/wodi'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/NodeQQ/src/poll.js:12:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```

然后就不知道怎么解决了。。

**Comment by gismanli** [comment]
sorry，谁是卧底模块没有开发完，比较忙，已经处理这个报错，pull一下最新代码吧~

**Comment by jshensh** [comment]
没事，还有您可以用 httpserver 来展示二维码么

**Comment by gismanli** [comment]
在OSX上开发的，没考虑linux系统，后续在优化吧~

**Comment by jshensh** [comment]
恩还有就是 smartQQ 有时候消息会发不出去，我找个 Android 协议写写看
