### ISSUE TITLE
两三天就要重新手机扫码登录一次是吗？

### ISSUE THREAD

**Issue by s749312025** [gismanli/NodeQQ#9]
RT，两三天就要重新手机扫码登录一次是吗？

**Comment by rocka** [comment]
目前看来是这样的，不知道有没又什么简单的解决办法。估计疼讯不久就要把这东西废掉了，能用一天是一天吧 = =

**Comment by s749312025** [comment]
快来看一下，现在不能用了  login.js的map
报错

K:\study\NodeQQ (master) (qq-bot@0.1.0)                                     
λ node app.js                                                               
down success                                                                
[Wed Mar 22 2017 11:27:43 GMT+0800 (中国标准时间)] INFO 登录 step1: 等待二维码校验结果.      
K:\study\NodeQQ\src\login.js:82                                             
        let ret = data.match(/\'(.*?)\'/g).map(function (i) {               
                                          ^                                 
                                                                            
TypeError: Cannot read property 'map' of null                               
    at K:\study\NodeQQ\src\login.js:82:43                                   
    at IncomingMessage.<anonymous> (K:\study\NodeQQ\libs\httpclient.js:86:20
    at emitNone (events.js:91:20)                                           
    at IncomingMessage.emit (events.js:186:7)                               
    at endReadableNT (_stream_readable.js:974:12)                           
    at _combinedTickCallback (internal/process/next_tick.js:74:11)          
    at process._tickCallback (internal/process/next_tick.js:98:9)           
                                                                            
K:\study\NodeQQ (master) (qq-bot@0.1.0)                                     
λ

**Comment by s749312025** [comment]
@Rocket1184 
@gismanli

**Comment by gismanli** [comment]
我来看下

**Comment by s749312025** [comment]
7.5的nodejs
应该没关系的，我过年的时候能在服务器上跑，然后我就停用了，今天想再去跑一下，然后就报错了

**Comment by rocka** [comment]
webQQ又增加了一个cookie验证，可以参见 https://github.com/Rocket1184/qq-bot-rebown/blob/master/src/qq/index.js#L50-L57

我的这个实现参考自 https://github.com/floatinghotpot/qqbot/commit/627cca6e93fc9cb2786928a6ae21ca762b31bd03

**Comment by s749312025** [comment]
我试一下，谢谢你们的帮助

**Comment by gismanli** [comment]
谢谢 @Rocket1184 ， 参考下他的实现， webqq 来回改，真是头痛  :(

**Comment by maicong** [comment]
`TypeError: Cannot read property 'map' of null` 这个问题我修复了，PR 已经合并了
